### ISSUE TITLE
Spurious error message: events are the same, but not the actions.

### ISSUE THREAD

**Issue by motib** [aseba-community/aseba#337] opened 2014-11-12 07:15 UTC
The event and the state condition in line 6 is the same as in line 5.

1. This should not be an error because the actions are different
(top vs. bottom leds).

2. The program is being run in basic mode and the error message should
not mention the "state condition" from advanced mode.
Strangely, if I click advanced mode, the error message now becomes
appropriate for basic mode:
The event in line 6 is the same as in line 5.

![colors](https://cloud.githubusercontent.com/assets/2620202/5006469/aa1259c6-6a4b-11e4-8cab-c72e2ee980e9.png)

**Comment by stephanemagnenat** [comment] 2015-02-10 08:29
This should be fixed by the implementation of the wish #350.

**Comment by sampla** [comment] 2015-02-10 10:02
1. Is not a bug, here is the correct program:
![screenshot from 2015-02-10 10 57 12](https://cloud.githubusercontent.com/assets/9136941/6125221/25623ede-b114-11e4-9ebe-afe5e2aa90ee.png)

2. Is fixed in #356

This has nothing to do with #350!

**Comment by stephanemagnenat** [comment] 2015-02-10 10:03
@motib please test and close if fixed.

**Comment by motib** [comment] 2015-02-10 13:10
It's not fixed in Windows build b4e79cb.
Should wait until tomorrow?

Concerning: "Is not a bug, here is the correct program".
Of course this is a better program now that multiple actions are supported,
but the program I posted is also correct (unless the semantics of VPL is changed)
and a user is likely to construct such a program.

**Comment by stephanemagnenat** [comment] 2015-02-10 13:13
> Should wait until tomorrow?
Yes, as the correction was committed this morning.

> the program I posted is also correct
It is not correct, as we now forbid to have twice the same parametrized event. We can discuss whether that is a good thing or not, but I chose that way because it made things simpler.

**Comment by motib** [comment] 2015-02-10 13:16
I'm OK with these semantics.

**Comment by motib** [comment] 2015-02-11 06:58
Windows implementation works. Thanks!!!

I raised 337 and could close it but I'm not sure of its
relationship with 350, 356, 357.

On Tue, Feb 10, 2015 at 3:13 PM, Stéphane Magnenat <notifications@github.com

**Comment by stephanemagnenat** [comment] 2015-02-11 07:04
@sampla implemented #350 yesterday, but I only merged it this morning, so it will be available in tomorrow's nightly build. For now I would close this issue, and then test tomorrow the new visual display of errors.

**Closed** 2015-02-11 07:18 UTC
Labels: Bug, Thymio VPL

**Comment by mbonani** [comment] 2015-02-11 07:25
We can exceptionaly make packages during day... Just tell me if needet and
if you plan some commit this morning so that I wait to ask launching the
script...


*Bonani Michael*
Tél.: +41 (0) 21 693 78 69
Mobile: +41 (0) 76 349 72 14

Association Mobsya
1023 Crissier
www.mobsya.org


2015-02-11 8:04 GMT+01:00 Stéphane Magnenat <notifications@github.com>:

**Comment by motib** [comment] 2015-02-11 07:44
Michael ... I don't see the urgency.
