### ISSUE TITLE
reordering event-action pairs is not clear

### ISSUE THREAD

**Issue by riedo** [aseba-community/aseba#263] opened 2013-11-15 16:54 UTC
Sometimes, if i reorder lines in VPL (I use development version, display pairs on 2 columns) new empty lines appear in the middle... Or maybe it's the last empty line that moves in the middle, so a new one is created? it is not very clear to me.

when I drag a pair it would be nice that I can visualise where it will go (e.g. other lines move in real time) (this was the utopic wish part)

**Comment by stephanemagnenat** [comment] 2015-03-17 18:04
@mbonani and @riedo, is this problem still present in latest 1.4 development versions?

**Comment by mbonani** [comment] 2015-03-18 09:35
for me it is an old bug related to 1.3.....

**Comment by stephanemagnenat** [comment] 2015-11-24 12:58
I agree, I close it. @riedo please open it again if the problem is still present in VPL 1.4

**Closed by stephanemagnenat** 2015-11-24 12:58 UTC
Labels: Thymio VPL, Wish
